"""
Data Analysis Module

Processes experiment results generated by the
Experiment Controller and computes statistical
summaries for the XR Testing Framework.
"""

__version__ = "1.0"

from .data_analysis import DataAnalysis