import json
from pathlib import Path

import pandas as pd


class DataAnalysis:
    """
    Component 5

    Reads experiment_results.csv generated by the
    Experiment Controller and produces:

    • analysis_summary.csv
    • statistics.json
    """

    def __init__(self):

        self.results_dir = Path(__file__).resolve().parents[2] / "results"

        self.input_file = self.results_dir / "experiment_results.csv"

        self.summary_file = self.results_dir / "analysis_summary.csv"

        self.statistics_file = self.results_dir / "statistics.json"

        self.df = None

    ###########################################################

    def load_results(self):

        if not self.input_file.exists():

            raise FileNotFoundError(
                f"Experiment results not found:\n{self.input_file}"
            )

        self.df = pd.read_csv(self.input_file)

        print(f"\nLoaded {len(self.df)} experiments.")

    ###########################################################

    def calculate_statistics(self):

        stats = {

            "Total Experiments": len(self.df),

            "Average Latency (ms)": round(
                self.df["Average Latency"].mean(), 2
            ),

            "Minimum Latency (ms)": round(
                self.df["Average Latency"].min(), 2
            ),

            "Maximum Latency (ms)": round(
                self.df["Average Latency"].max(), 2
            ),

            "Average Packet Loss (%)": round(
                self.df["Packet Loss %"].mean(), 2
            ),

            "Average Throughput (Mbps)": round(
                self.df["Throughput"].mean(), 2
            ),

            "Average Runtime (s)": round(
                self.df["Runtime(s)"].mean(), 2
            )

        }


        return stats

    ###########################################################

    def save_statistics(self, stats):

        with open(self.statistics_file, "w") as f:

            json.dump(
                stats,
                f,
                indent=4
            )

        print("statistics.json created.")

    ###########################################################

    def create_summary(self):

        summary = self.df.groupby(
            [
                "Latency(ms)",
                "Loss(%)",
                "Jitter(ms)",
                "Bandwidth(Mbps)"
            ]
        ).agg(
            {
                "Average Latency": "mean",
                "Throughput": "mean",
                "Packet Loss %": "mean",
             "Packets": "mean",
                "Runtime(s)": "mean"
            }
        ).reset_index()

        summary.to_csv(
            self.summary_file,
            index=False
     )

        print("analysis_summary.csv created.")

    ###########################################################

    def best_experiment(self):

        idx = self.df["Throughput"].idxmax()

        return self.df.loc[idx]

    ###########################################################

    def worst_experiment(self):

        idx = self.df["Packet Loss %"].idxmax()

        return self.df.loc[idx]

    ###########################################################

    def print_report(self):

        best = self.best_experiment()

        worst = self.worst_experiment()

        print("\n========== ANALYSIS REPORT ==========\n")

        print("Best Experiment")

        print(best)

        print()

        print("Worst Experiment")

        print(worst)

        print()

    ###########################################################

    def run(self):

        self.load_results()

        stats = self.calculate_statistics()

        self.save_statistics(stats)

        self.create_summary()

        self.print_report()

        print("Analysis complete.")


###############################################################

def main():

    analysis = DataAnalysis()

    analysis.run()


###############################################################

if __name__ == "__main__":

    main()